version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb-dev
        ports:
            - 27017:27017 
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
    redis:
      image: redis:latest
      command: redis-server --port 6379
      container_name: redis-dev
      ports:
        - 6379:6379

    mysql:
      image: mysql:8.0
      container_name: mysql
      ports:
        - 3306:3306 # HOST:CONTAINER
      environment:
        MYSQL_ROOT_PASSWORD: admin
      command:
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_general_ci